name: Continuous Delivery

on:
  workflow_dispatch:
  push:

env:
  PACT_BROKER_BASE_URL: https://paulogoncalves.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  COMMIT: ${{ github.sha }}
  BRANCH: ${{ github.ref }}

jobs:
  dispatch:
    runs-on: ubuntu-18.04
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
        repository: ServeRest/ServeRest
        event-type: consumer-dispatch
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
