name: Repository Dispatch
on:
  repository_dispatch:
    types: [dispatch-message]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload }}
      - run: echo ${{ github.event.client_payload.url }}
      - run: echo ${{ github.event.client_payload.job_name }}
